Fixed an error in running in version 2.0.0
zmeyc/telegram-bot-swift pull request #104
Opened 2020-05-29 20:47 UTC by hdcola

Using an Int64 directly in the SendMessage function is no longer straightforward.

2020-06-02 22:29 UTC, cipi1965 requested changes

2020-06-02 22:29 UTC, cipi1965 commented on README.md
> +let fromId: fromId = ChatId.chat(12345678) // your user id
I'm not sure of this change, the correct type is ChatId

2020-06-02 22:30 UTC, hdcola commented on README.md
> +let fromId: fromId = ChatId.chat(12345678) // your user id
I use ChatId(Int64) which does not work.

2020-06-02 22:31 UTC, hdcola commented on README.md
> +let fromId: fromId = ChatId.chat(12345678) // your user id
I prefer to use Int64 directly as a chatId parameter, but it's true that this doesn't work.

2020-06-02 22:31 UTC, cipi1965 commented on README.md
> +let fromId: fromId = ChatId.chat(12345678) // your user id
The row should be:
`let fromId: ChatId = ChatId.chat(12345678)`

fromId does not exists as type

2020-06-02 22:41 UTC, zmeyc commented on README.md
> +let fromId: fromId = ChatId.chat(12345678) // your user id
I think this will also work:
```
let fromId: ChatId = .chat(12345678)
```

2020-06-02 22:44 UTC, zmeyc commented on README.md
> +let fromId: fromId = ChatId.chat(12345678) // your user id
ChatId can be a string (channel name), so we can't declare variable directly as Int64.

2020-06-02 22:45 UTC, hdcola commented on README.md
> +let fromId: fromId = ChatId.chat(12345678) // your user id
Yes, this can work.But the original code that uses Int64 directly must not work.

2020-06-02 23:09 UTC, hdcola commented
I changed it to .chat()

2020-06-02 23:23 UTC, hdcola commented
Anyway I just wanted to say that the current README.MD in

`
let fromId: Int64 = 12345678 // your user id
bot.sendMessageSync(fromId, "Hello!") // blocks until the message is sent
bot.sendMessageSync(fromId, "Bye.")
`

It's not going to work.

2020-06-03 06:07 UTC, cipi1965 approved these changes

2020-06-03 06:07 UTC, cipi1965 commented
Now it's perfect, merging

2020-06-03 06:07 UTC, merged